---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python
  roles:
  - common

- hosts: tftp
  become: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python
  roles:
  - tftp
